development:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: root
  password: ''
  database: 'departure_scraper_dev'
test:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: root
  password: ''
  database: 'departure_scraper_test'
