development:
  weather:
    api_key: 29adf6999564d80eed93afc7f41c9401
    base_url: http://api.openweathermap.org/
  viennaairport:
    url: https://www.viennaairport.com/jart/prj3/va/main.jart?rel=en&reserve-mode=active&content-id=1249344074230
test:
  weather:
    api_key: 29adf6999564d80eed93afc7f41c9401
    base_url: http://api.openweathermap.org/
  viennaairport:
    url: https://www.viennaairport.com/jart/prj3/va/main.jart?rel=en&reserve-mode=active&content-id=1249344074230
